[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "redux-pip-packages"
version = "0.1.1"
description = "Redux's internal Python packages (mt5_sdk, render_requests_helper)"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"redux_py_packages" = ["**/*"]