[build-system]
requires = ["setuptools>=68", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "redux-pip-packages"
description = "Redux's internal Python packages (mt5_sdk, render_requests_helper)"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "dependencies"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"redux_py_packages" = ["**/*"]

[tool.setuptools_scm]